# The Guessing Game #
# ================= #

# Brief: Guessing the correct random number generated by the 'random.randint()' function
# Concepts Used: Functions, Loops, Conditional Execution

# ----- Importing Libraries ----- #

import random

# ----- Welcome Message ----- #

print("\n", "The Guessing Game", "\n", "=================\n")

msg = '''
We got two games here and you need to choose one of them:

G1: Human Guessing (Computer will choose a random number and you need to guess it
G2: Computer Guessing (You will choose a secret number and your computer will guess it

Let's start the game !!!
'''

# ------ Start of Program ----- #

def HumanGuess(x):
    random_num = random.randint(1, x)
    guess = 0
    while guess != random_num:
        guess = int(input(f'Guess a number between 1 and {x}: '))
        if guess < random_num:
            print('Too Low !!! Guess again...')
        elif guess > random_num:
            print('Too High !!! Guess again...')
    
    print(f'Yay, Congrats !!! You have guessed the number: {random_num}')

def ComputerGuess(x):
    low = 1
    high = x
    feedback = ''
    
    input(f'Choose your secret number between 1 to {x}: ')
    
    while feedback != 'c':
        if low != high:
            guess = random.randint(low, high)
        else:
            guess = low
        
        feedback = input(f'Is {guess} too high (H), too low (L), or, correct (C) ?? : ').lower()
        if feedback == 'h':
            high = guess - 1
        elif feedback == 'l':
            low = guess + 1
    
    print(f'Yay, Congrats !!! Your computer guessed your secret number: {guess}')

if __name__ == '__main__':
    
    print(msg)
    
    choice = input('Provide "G1" for "Game-1" and "G2" for "Game-2": ').lower()
    
    if choice == 'g1':
        HumanGuess(100)
    elif choice == 'g2':
        ComputerGuess(100)
    else:
        print('Please provide a valid game to play !! Try Again...')
    
# ------ End of Program ----- #