# Stone Paper Scissors #
# ==================== #

# Brief: Guessing the correct random number generated by the 'random.randint()' function
# Concepts Used: Functions, Loops, Conditional Execution

# ----- Importing Libraries ----- #

import random

# ----- Welcome Message ----- #

print("\n", "!!! Stone Paper Scissors !!!", "\n", "============================\n")

msg = '''
You have 3 choices to choose from:

r : for Rock
p : for Paper
s : for Scissor

Let's Play !!!
'''


# ------ Start of Program ----- #

def IsWin(player, opponent):
    if (player == 'r' and opponent == 's') or (player == 's' and opponent == 'p') or (player == 'p' and opponent == 'r'):
        return True

def Play():
    user = input('What\'s your choice:\n"r" for Rock, "p" for Paper & "s" for Scissors: ').lower()
    computer = random.choice(['r', 'p', 'c'])
    
    if user == computer:
        return 'It\'s a tie !!!'
    
    if IsWin(user, computer):
        return 'You Won !!!'
    
    return 'You Lost !!!'

if __name__ == '__main__':
    print(msg)
    result = Play()
    print(result)

# ------ End of Program ----- #